version: '3.8'

services:
  # Backend servisi
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/app.db
      - chromadb_data:/app/chromadb
    environment:
      - OLLAMA_API_BASE=http://ollama:11434/api
      - MODEL_NAME=phi4:latest
      - WHISPER_MODEL=base
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mentornet

  # Frontend servisi
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mentornet

  # Ollama servisi (AI modeli çalıştırır)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    restart: unless-stopped
    networks:
      - mentornet

volumes:
  sqlite_data:
    driver: local
  chromadb_data:
    driver: local
  ollama_data:
    driver: local

networks:
  mentornet:
    driver: bridge